version: "3"
services: 
    flask:
        image: flask_http_status_codes
        build: ./flask
        container_name: flask_http_status_codes
        volumes: 
            - ./flask/app:/usr/src/app
        networks: 
            - net_http_status_codes
    nginx:
        image: nginx_http_status_codes
        build: ./nginx
        container_name: nginx_http_status_codes
        networks: 
            - net_http_status_codes
networks: 
    net_http_status_codes:
        driver: bridge