version: '3.9'
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
            target: development
        image: return_http_status_code_dev
        container_name: return_http_status_code_dev
        ports:
            - "5000:5000"
        volumes:
            - ./:/app
        tty: true
