version: "3"
services: 
    flask:
        image: flask_http_status_codes
        build: 
            context: ./flask
            dockerfile: Dockerfile
        container_name: flask_http_status_codes
        volumes: 
            - ./flask/app:/usr/src/app
        ports: 
            - "8004:8000"
        networks: 
            - net_http_status_codes
        tty: true
        command: bash -c 'gunicorn -w 2 -b 0.0.0.0:8000 app:app'
    nginx:
        image: nginx_http_status_codes
        build: 
            context: ./nginx
            dockerfile: Dockerfile
        container_name: nginx_http_status_codes
        networks: 
            - net_http_status_codes
networks: 
    net_http_status_codes:
        driver: bridge